image: ubuntu:18.04

stages:
  - build

build:
  stage: build
  retry: 2
  cache:
    paths:
      - ./
    key: "$CI_COMMIT_REF_SLUG"
  script:
    - apt install -y build-essential zlib1g-dev uuid-dev libdigest-sha-perl libelf-dev bc bzip2 bison flex git gnupg iasl m4 nasm patch python  wget gnat cpio ccache pkg-config cmake libusb-1.0-0-dev pkg-config
    - git fetch origin 
    - git reset --hard origin/$CI_COMMIT_REF_NAME
    - make BOARD=x230-libremkey || (find ./build/log/ -cmin 1|xargs tail; exit 1)
    - echo "x230 hashes:"
    - cat ./build/x230-libremkey/hashes.txt
  artifacts:
    paths:
      - ./build/x230-libremkey/coreboot.rom
      - ./build/x230-libremkey/x230-libremkey-bottom.rom
      - ./build/x230-libremkey/x230-libremkey-top.rom
      - ./build/x230-libremkey/hashes.txt
