version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - run:
          name: Install dependencies
          command: |
            apt install -y build-essential zlib1g-dev uuid-dev libdigest-sha-perl libelf-dev bc bzip2 bison flex git gnupg iasl m4 nasm patch python  wget gnat cpio ccache pkg-config cmake libusb-1.0-0-dev pkg-config

      - checkout

      - run:
          name: Bootstrap make
          command: |
            make bootstrap

      - run:
          name: Bootstrap coreboot-gcc
          command: |
            ./build/make-4.2.1/make \
                V=1 \
                BOARD=x230-libremkey \
                coreboot-gcc


      - run:
          name: x230-libremkey
          command: |
            ./build/make-4.2.1/make \
                V=1 \
                BOARD=x230-libremkey \

      - store-artifacts:
          path: build/x230-libremkey/coreboot.rom
      - store-artifacts:
          path: build/x230-libremkey/x230-libremkey-bottom.rom
      - store-artifacts:
          path: build/x230-libremkey/x230-libremkey-top.rom	
      - store-artifacts:
          path: build/x230-libremkey/hashes.txt

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
